package com.wqyx;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-25T16:34:29.080+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "idVerifyService", 
                  wsdlLocation = "http://121.199.14.98/wqyxservice/services/idVerifyService?wsdl",
                  targetNamespace = "http://www.wqyx.com") 
public class IdVerifyService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.wqyx.com", "idVerifyService");
    public final static QName IdVerifyServiceHttpPort = new QName("http://www.wqyx.com", "idVerifyServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://121.199.14.98/wqyxservice/services/idVerifyService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IdVerifyService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://121.199.14.98/wqyxservice/services/idVerifyService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IdVerifyService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IdVerifyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IdVerifyService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IdVerifyServicePortType
     */
    @WebEndpoint(name = "idVerifyServiceHttpPort")
    public IdVerifyServicePortType getIdVerifyServiceHttpPort() {
        return super.getPort(IdVerifyServiceHttpPort, IdVerifyServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IdVerifyServicePortType
     */
    @WebEndpoint(name = "idVerifyServiceHttpPort")
    public IdVerifyServicePortType getIdVerifyServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(IdVerifyServiceHttpPort, IdVerifyServicePortType.class, features);
    }

}
