package com.wqyx;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-25T16:34:29.045+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.wqyx.com", name = "idVerifyServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface IdVerifyServicePortType {

    @WebResult(name = "out", targetNamespace = "http://www.wqyx.com")
    @RequestWrapper(localName = "verifyService", targetNamespace = "http://www.wqyx.com", className = "com.wqyx.VerifyService")
    @WebMethod
    @ResponseWrapper(localName = "verifyServiceResponse", targetNamespace = "http://www.wqyx.com", className = "com.wqyx.VerifyServiceResponse")
    public java.lang.String verifyService(
        @WebParam(name = "in0", targetNamespace = "http://www.wqyx.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://www.wqyx.com")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://www.wqyx.com")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://www.wqyx.com")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://www.wqyx.com")
        java.lang.String in4,
        @WebParam(name = "in5", targetNamespace = "http://www.wqyx.com")
        java.lang.String in5,
        @WebParam(name = "in6", targetNamespace = "http://www.wqyx.com")
        java.lang.String in6
    );
}
